#!/bin/bash
# --------------------------------------------------------
checkfolder(){
    if [ ! -f ${1} ]; then
        mkdir $1
    fi
}
loadstrings(){
    defaultuser="giomar"
    # setup vim ------------------------------------
    titlesvim="SETTING UP VIM"
    command_pip_vim="sudo -u %1 pip install"
    pkgs_pip_vim="virtualenv pynvim python-language-server flake8 pylint black jedi"
    npm_install_folder="/home/%1/node_modules"
    prefix="-- prefix %1"
    command_npm_vim="sudo -u %1 npm install"
    pkgs_npm_vim="neovim eslint eslint-config-airbnb-base --save-dev"	
}
loadstrings
#checkfolder "${npm_install_folder//%1/$defaultuser}"
#echo "${prefix//%1/${npm_install_folder//%1/$defaultuser}}"
echo "${command_npm_vim//%1/$defaultuser}${prefix//%1/${npm_install_folder//%1/$defaultuser}}"
#echo "${command_npm_vim//%1/hola//%2/${npm_install_folder//%1/$defaultuser}}"
